// Generated by gencpp from file pal_video_recording_msgs/StopRecording.msg
// DO NOT EDIT!


#ifndef PAL_VIDEO_RECORDING_MSGS_MESSAGE_STOPRECORDING_H
#define PAL_VIDEO_RECORDING_MSGS_MESSAGE_STOPRECORDING_H

#include <ros/service_traits.h>


#include <pal_video_recording_msgs/StopRecordingRequest.h>
#include <pal_video_recording_msgs/StopRecordingResponse.h>


namespace pal_video_recording_msgs
{

struct StopRecording
{

typedef StopRecordingRequest Request;
typedef StopRecordingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopRecording
} // namespace pal_video_recording_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pal_video_recording_msgs::StopRecording > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pal_video_recording_msgs::StopRecording&) { return value(); }
};

template<>
struct DataType< ::pal_video_recording_msgs::StopRecording > {
  static const char* value()
  {
    return "pal_video_recording_msgs/StopRecording";
  }

  static const char* value(const ::pal_video_recording_msgs::StopRecording&) { return value(); }
};


// service_traits::MD5Sum< ::pal_video_recording_msgs::StopRecordingRequest> should match
// service_traits::MD5Sum< ::pal_video_recording_msgs::StopRecording >
template<>
struct MD5Sum< ::pal_video_recording_msgs::StopRecordingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pal_video_recording_msgs::StopRecording >::value();
  }
  static const char* value(const ::pal_video_recording_msgs::StopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_video_recording_msgs::StopRecordingRequest> should match
// service_traits::DataType< ::pal_video_recording_msgs::StopRecording >
template<>
struct DataType< ::pal_video_recording_msgs::StopRecordingRequest>
{
  static const char* value()
  {
    return DataType< ::pal_video_recording_msgs::StopRecording >::value();
  }
  static const char* value(const ::pal_video_recording_msgs::StopRecordingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pal_video_recording_msgs::StopRecordingResponse> should match
// service_traits::MD5Sum< ::pal_video_recording_msgs::StopRecording >
template<>
struct MD5Sum< ::pal_video_recording_msgs::StopRecordingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pal_video_recording_msgs::StopRecording >::value();
  }
  static const char* value(const ::pal_video_recording_msgs::StopRecordingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pal_video_recording_msgs::StopRecordingResponse> should match
// service_traits::DataType< ::pal_video_recording_msgs::StopRecording >
template<>
struct DataType< ::pal_video_recording_msgs::StopRecordingResponse>
{
  static const char* value()
  {
    return DataType< ::pal_video_recording_msgs::StopRecording >::value();
  }
  static const char* value(const ::pal_video_recording_msgs::StopRecordingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAL_VIDEO_RECORDING_MSGS_MESSAGE_STOPRECORDING_H
