// Generated by gencpp from file humanoid_nav_msgs/PlanFootstepsBetweenFeetRequest.msg
// DO NOT EDIT!


#ifndef HUMANOID_NAV_MSGS_MESSAGE_PLANFOOTSTEPSBETWEENFEETREQUEST_H
#define HUMANOID_NAV_MSGS_MESSAGE_PLANFOOTSTEPSBETWEENFEETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <humanoid_nav_msgs/StepTarget.h>
#include <humanoid_nav_msgs/StepTarget.h>
#include <humanoid_nav_msgs/StepTarget.h>
#include <humanoid_nav_msgs/StepTarget.h>

namespace humanoid_nav_msgs
{
template <class ContainerAllocator>
struct PlanFootstepsBetweenFeetRequest_
{
  typedef PlanFootstepsBetweenFeetRequest_<ContainerAllocator> Type;

  PlanFootstepsBetweenFeetRequest_()
    : start_left()
    , start_right()
    , goal_left()
    , goal_right()  {
    }
  PlanFootstepsBetweenFeetRequest_(const ContainerAllocator& _alloc)
    : start_left(_alloc)
    , start_right(_alloc)
    , goal_left(_alloc)
    , goal_right(_alloc)  {
  (void)_alloc;
    }



   typedef  ::humanoid_nav_msgs::StepTarget_<ContainerAllocator>  _start_left_type;
  _start_left_type start_left;

   typedef  ::humanoid_nav_msgs::StepTarget_<ContainerAllocator>  _start_right_type;
  _start_right_type start_right;

   typedef  ::humanoid_nav_msgs::StepTarget_<ContainerAllocator>  _goal_left_type;
  _goal_left_type goal_left;

   typedef  ::humanoid_nav_msgs::StepTarget_<ContainerAllocator>  _goal_right_type;
  _goal_right_type goal_right;





  typedef boost::shared_ptr< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanFootstepsBetweenFeetRequest_

typedef ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<std::allocator<void> > PlanFootstepsBetweenFeetRequest;

typedef boost::shared_ptr< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest > PlanFootstepsBetweenFeetRequestPtr;
typedef boost::shared_ptr< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest const> PlanFootstepsBetweenFeetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator1> & lhs, const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_left == rhs.start_left &&
    lhs.start_right == rhs.start_right &&
    lhs.goal_left == rhs.goal_left &&
    lhs.goal_right == rhs.goal_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator1> & lhs, const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace humanoid_nav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a081711eb51a4a4283b2b9f345efe272";
  }

  static const char* value(const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa081711eb51a4a42ULL;
  static const uint64_t static_value2 = 0x83b2b9f345efe272ULL;
};

template<class ContainerAllocator>
struct DataType< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humanoid_nav_msgs/PlanFootstepsBetweenFeetRequest";
  }

  static const char* value(const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "humanoid_nav_msgs/StepTarget start_left\n"
"humanoid_nav_msgs/StepTarget start_right\n"
"humanoid_nav_msgs/StepTarget goal_left\n"
"humanoid_nav_msgs/StepTarget goal_right\n"
"\n"
"================================================================================\n"
"MSG: humanoid_nav_msgs/StepTarget\n"
"# Target for a single stepping motion of a humanoid's leg\n"
"\n"
"geometry_msgs/Pose2D pose   # step pose as relative offset to last leg\n"
"uint8 leg                   # which leg to use (left/right, see below)\n"
"\n"
"uint8 right=0               # right leg constant\n"
"uint8 left=1                # left leg constant\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_left);
      stream.next(m.start_right);
      stream.next(m.goal_left);
      stream.next(m.goal_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanFootstepsBetweenFeetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::humanoid_nav_msgs::PlanFootstepsBetweenFeetRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_left: ";
    s << std::endl;
    Printer< ::humanoid_nav_msgs::StepTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.start_left);
    s << indent << "start_right: ";
    s << std::endl;
    Printer< ::humanoid_nav_msgs::StepTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.start_right);
    s << indent << "goal_left: ";
    s << std::endl;
    Printer< ::humanoid_nav_msgs::StepTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_left);
    s << indent << "goal_right: ";
    s << std::endl;
    Printer< ::humanoid_nav_msgs::StepTarget_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMANOID_NAV_MSGS_MESSAGE_PLANFOOTSTEPSBETWEENFEETREQUEST_H
